# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='categoria',
            field=models.CharField(default='Paginas Web', max_length=120),
        ),
    ]
