# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0002_plantilla_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='destacado',
            field=models.BooleanField(default=True),
        ),
    ]
