# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0003_auto_20190120_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='categoria',
            field=models.CharField(default='P\xe1ginas Web', max_length=120),
        ),
    ]
