# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrolladore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('estudios', models.CharField(blank=True, max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
