# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 08:49
from __future__ import unicode_literals

import desarrolladores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrolladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('marcado', models.SlugField(blank=True, unique=True)),
                ('cumpleanos', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=desarrolladores.models.upload_image_path)),
                ('activo', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('estudios', models.CharField(blank=True, max_length=100)),
                ('cv', models.FileField(blank=True, null=True, upload_to=desarrolladores.models.upload_cv_path)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Desarrolladore',
        ),
    ]
