# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrolladores', '0003_desarrollador_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollador',
            name='cumpleanos',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='desarrollador',
            name='destacado',
            field=models.BooleanField(default=True),
        ),
    ]
