# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-22 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrolladores', '0004_auto_20190120_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollador',
            name='cumpleanos',
            field=models.DateField(),
        ),
    ]
