# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-24 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrolladores', '0005_auto_20190122_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='desarrollador',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='desarrollador',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='desarrollador',
            name='twiter',
            field=models.URLField(blank=True),
        ),
    ]
